version: '2.1'
orbs:
  terraform: circleci/terraform@3.1

jobs:
  test:
    executor: terraform/default
    steps:
      - checkout
      # - terraform/init:
      #     path: .
      # - terraform/validate:
      #     path: .
      # - terraform/fmt:
      #     path: .
      # - terraform/plan:
      #     path: .
      # - terraform/apply:
      #     path: .
    # working_directory: ~/src


workflows:
  single-job-lifecycle:
    jobs:
      - test
